CREATE TABLE DELIVERY(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CLIENT_ID BIGINT NOT NULL,
	TAXA DECIMAL(10,2) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	DATE_REQUEST DATETIME NOT NULL,
	DATE_FINALIZATION DATETIME,
	
	
	RECEIVER_NAME VARCHAR(60) NOT NULL,
	RECEIVER_PLACE VARCHAR(255) NOT NULL,
	RECEIVER_NUMBER VARCHAR(30) NOT NULL,
	RECEIVER_COMPLEMENT VARCHAR(60) NOT NULL,
	RECEIVER_NEIGHBORHOOD VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_CLIENT_DELIVERY FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);
/*ALTER TABLE DELIVERY ADD CONSTRAINT FK_CLIENT_DELIVERY FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(id)*/