CREATE TABLE OCCURRENCE(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DELIVERY_ID BIGINT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	REGISTER_DATE DATETIME NOT NULL,
	
	PRIMARY KEY (ID),
	CONSTRAINT FK_OCCURRENCE_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY(ID)
)